version: "3.6"
services:
  db:
    container_name: nextjs-hasura-fullstack-db
    image: postgres:11.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    container_name: nextjs-hasura-fullstack-db-admin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
  backend:
    container_name: nextjs-hasura-fullstack-backend
    image: nextjs-hasura-fullstack-backend
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/postgres
      PORT: 8080
      HASURA_GRAPHQL_ADMIN_SECRET: "secret@123"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqPGYul8KnfYM1pji+Dn9\nvB7fQ4MOyTgzN0c5viONOBiBtDB3G1weoRhoZh7V+n1WjftKWQZezwUOtL8CQXrg\nIgjXe7aKljiPYZgf6QR2GuKHW/EKewV86+rhGK5uI76CjbmXqbKlNe6+SXANsufs\nlRv7O8h+eCK899Uf+jUtaxWFbXawB7ukdcrjr+89QqWJ/VAZ2da3u3ttlPJY13Pp\ndtGNjBQhwj2nFodOqx65gvUZ8bAbihRSu6cxoGZl1gK3DHScCGIi3I23MwiXoWQE\nZuPEjgLCGBJ9T5H/YQWxVvq2b9n9olOOY4uXsoJ0Z/BCFD3vV3zZdSY7va4OeAKk\n1QIDAQAB\n-----END PUBLIC KEY-----"}'
volumes:
  db_data:
