version: "3.6"
services:
  db:
    container_name: nextjs-hasura-fullstack-db
    image: postgres:11.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    container_name: nextjs-hasura-fullstack-backend
    image: nextjs-hasura-fullstack-backend
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/postgres
      PORT: 8080
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
volumes:
  db_data:
